### ISSUE TITLE
Media Page

### ISSUE THREAD

**Issue by kpmaio** [CodeForCharlotte/codeforcharlotte.org#128]
Update the media content

**Comment by Jillzey** [comment]
Pull media info from current site at http://www.codeforcharlotte.org/media.html

**Comment by Jillzey** [comment]
Content is done and updated.  

Formatting requests: 
1. Add sidebar on left
2. Make Image Gallery thumbnail smaller to match Video size.
3. Add video next to existing video to create columns. (Repeat video selection and will update with correct video link)
4. Add image gallery thumbnails next to existing thumbnail to create columns.  (Repeat image gallery if necessary so that content can just be updated)
